### PR TITLE
Add this Web dev Project random quote machine

### PR DESCRIPTION
**Pull request by Chayandev**
**This project created using html,css and js , Random quote Generator machine.**

### CODE REVIEW

**Comment by Chayandev** [comment]
@Ash-KODES Please have a look.

**Comment by Ash-KODES** [comment]
> @Ash-KODES Please have a look.

Please add a readme to your project and a live hosted link of the same.

**Comment by Chayandev** [comment]
@Ash-KODES Please have a look , I have added deployed link  and readme.

**Comment by noobshubham** [comment]
Please let me know if this is included in Hacktoberfest 2022. because this year numerous comparable repos are not accepted

**Comment by Chayandev** [comment]
Yes this is included.

**Comment by noobshubham** [comment]
Thanks Buddy!

**Pull request merged**
