### PR TITLE
Add MauryaD information

### PR DESCRIPTION
**Pull request by MauryaD**

### CODE REVIEW

**Comment by MauryaD** [comment]
Please review and merge the changes. Also please add Hacktoberfest related labels to PR. 

Thanks!!

**Comment by Ash-KODES** [comment]
Add your Project in project directory.

**Comment by MauryaD** [comment]
Hi @Ash-KODES , added PR #50 . Please review and merge.
Also, I would request you to add Hacktober tags to PRs please.

**Comment by MauryaD** [comment]
Hi @Ash-KODES , could you please add hacktober fest labels to this PR.

Thanks!!

**Pull request merged**
