### PR TITLE
added a favicon and contributor

### PR DESCRIPTION
**Pull request by Janhvi52**

### CODE REVIEW

**Comment by Ash-KODES** [comment]
Please add your project and refer the readme for the same.

**Comment by Janhvi52** [comment]
> Please add your project and refer the readme for the same.

done! 
can refer now

**Comment by Ash-KODES** [comment]
> > Please add your project and refer the readme for the same.
> 
> done! can refer now

You need upload your projects folder along with the changes you have done. [Here ](https://github.com/GDSC-IET-LUCKNOW/Showcase-Hacktoberfest-2022/tree/main/Projects)

**Comment by Ash-KODES** [comment]
Please refer this if facing problems https://github.com/GDSC-IET-LUCKNOW/Showcase-Hacktoberfest-2022/pull/6

**Comment by Janhvi52** [comment]
> > > Please add your project and refer the readme for the same.
> > 
> > 
> > done! can refer now
> 
> You need upload your projects folder along with the changes you have done. [Here ](https://github.com/GDSC-IET-LUCKNOW/Showcase-Hacktoberfest-2022/tree/main/Projects)

i hope its done now

i have also added a fascinating favicon to your showcase page 
issue #17 
 hope you like it! @Ash-KODES

**Comment by Ash-KODES** [comment]
Great ! @Janhvi52

**Comment by Ash-KODES** [comment]
FIXES #17

**Pull request merged**
